In [11]:
# Add libraries
import pandas as pd

# Import data 
bp = pd.read_csv("Backpack.csv")

# Remove unnamed columns
bp.filter(["BackpackWeight", "BodyWeight", "Ratio", "BackProblems", "Major", "Year", "Sex", "Status", "Units"])

# Rewrite csv
bp.to_csv("Backpack.csv")

In [12]:
bp.head()

,Unnamed: 0.8,Unnamed: 0.7,Unnamed: 0.6,Unnamed: 0.5,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,BackpackWeight,BodyWeight,Ratio,BackProblems,Major,Year,Sex,Status,Units
0,0,0,0,0,0,0,0,0,0,9,125,0.072000,1,Bio,3,Female,U,13
1,1,1,1,1,1,1,1,1,4,8,180,0.044444,0,EE,2,Female,U,14
2,2,2,2,2,2,2,2,2,6,8,170,0.047059,0,CM,3,Male,U,15
3,3,3,3,3,3,3,3,3,10,8,135,0.059259,0,Bus,3,Female,U,15
4,4,4,4,4,4,4,4,4,14,12,125,0.096000,1,CS,3,Female,U,12